resource_types:
  - name: rsync-resource
    type: docker-image
    source:
      repository: registry.barrucadu.dev/rsync-resource
      username: registry
      password: ((docker-registry-password))

resources:
  - name: builder-image
    type: docker-image
    source:
      repository: registry.barrucadu.dev/memo-builder
      username: registry
      password: ((docker-registry-password))
  - name: weeknotes-git
    type: git
    source:
      uri: https://github.com/barrucadu/weeknotes.barrucadu.co.uk.git
  - name: weeknotes-rsync
    type: rsync-resource
    source:
      server: carcosa.barrucadu.co.uk
      remote_dir: /persist/srv/http/barrucadu.co.uk/weeknotes
      private_key: ((carcosa-ssh-private-key))

jobs:
  - name: update-pipeline
    plan:
      - get: weeknotes-git
        trigger: true
      - set_pipeline: weeknotes-barrucadu-co-uk
        file: weeknotes-git/concourse/pipeline.yml

  - name: build-and-deploy
    serial: true
    plan:
      - get: builder-image
      - get: weeknotes-git
        trigger: true
      - task: build-site
        image: builder-image
        params:
          OUT_DIR: weeknotes
        config:
          platform: linux
          inputs:
            - name: weeknotes-git
          outputs:
            - name: site
          run:
            dir: weeknotes-git
            path: sh
            args:
              - -cex
              - |
                virtualenv venv
                source venv/bin/activate
                pip install -r requirements-freeze.txt
                PATH=.:$PATH ./build --out="../site/${OUT_DIR}"
      - put: weeknotes-rsync
        params:
          path: site/weeknotes
          rsync_args:
            - --delete
